### ISSUE TITLE
[Suggestion]: Additional support for other mods

### ISSUE THREAD

**Issue by SiverDX** [Sonnenlicht-as/Trajectory-Estimation#1]
The Bumblezone:
https://github.com/TelepathicGrunt/Bumblezone/blob/1.20.x-Arch/common/src/main/java/com/telepathicgrunt/the_bumblezone/items/StingerSpearItem.java

Creatures and Beasts:
https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/blob/1.18/src/main/java/com/cgessinger/creaturesandbeasts/items/SpearItem.java

Alex's Caves:
https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/java/com/github/alexmodguy/alexscaves/server/item/LimestoneSpearItem.java

https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/java/com/github/alexmodguy/alexscaves/server/item/ExtinctionSpearItem.java

**Comment by Sonnenlicht-as** [comment]
Hi! It's a great suggestion, they'll be added soon
