### ISSUE TITLE
和tetra同时使用时出现错误

### ISSUE THREAD

**Issue by ZouGuaiJue** [Sonnenlicht-as/Trajectory-Estimation#10]
### 版本信息
MC版本：1.20.1
forge版本：47.3.0
弹道估计版本：1.0.3（当前最新版）
tetra版本：6.4.0（当前最新版）

### 问题
1.使用tetra的弓时，渲染轴偏转（视角上抬时，渲染弹道向左旋转）
![fd110f409017089dc85d91c70f94b5f](https://github.com/user-attachments/assets/1c997980-ceb1-4aca-94ca-a9be36834282)

2.使用tetra的弩时，游戏崩溃
[错误报告-2024-10-7_12.05.50.zip](https://github.com/user-attachments/files/17272723/-2024-10-7_12.05.50.zip)

**Comment by ZouGuaiJue** [comment]
![Uploading fd110f409017089dc85d91c70f94b5f.png…]()

**Comment by MistyOrchid** [comment]
在最新的小版本中已修复
