### ISSUE TITLE
I need to support version 1.18.0 of Minecraft , thank you!

### ISSUE THREAD

**Issue by Tan-TanZi** [Sonnenlicht-as/Trajectory-Estimation#4]
I need to support version 1.18.0 of Minecraft , thank you!

**Comment by Tan-TanZi** [comment]
1.18.2 cannot run normally in 1.18.0, which is too regrettable

**Comment by Sonnenlicht-as** [comment]
This is a temporary version and will not be released on other platforms for the time being. The release version will be added after the next version is updated.
None of the mods supported in 1.0.2 exist in 1.18, so there are only vanilla items.
https://github.com/Sonnenlicht-as/Trajectory-Estimation/releases/tag/1.0.2-1.18-beta
