### ISSUE TITLE
联动的mod使用旧版本时启动崩溃

### ISSUE THREAD

**Issue by mjt233** [Sonnenlicht-as/Trajectory-Estimation#5]
## 复现步骤
安装有模组支持的第三方联动mod，但不是最新的版本，如：alex的洞穴-1.0.8

同该模组一起加载时会出现以下异常导致游戏退出

![image](https://github.com/Sonnenlicht-as/Trajectory-Estimation/assets/54613529/7c8b6425-2800-47e5-a66b-560f539e75bc)

当我添加这个模组后，如果同时有多个mod因为版本比较旧没有更新时，只能启动一次报错一次再更新一个mod，直到可以启动游戏

## 可能的原因
alex的洞穴-1.0.8 版本没有物品 Extinction Spear(灭绝长矛)，加载不到类`com.github.alexmodguy.alexscaves.server.item.ExtinctionSpearItem`

## 不太了解MC模组的开发，提供了点想当然的想法

是否可以添加下异常处理？或通过反射进行判断？
:)

**Comment by Sonnenlicht-as** [comment]
感谢反馈，会解决的
