### ISSUE TITLE
Conflict with Ender Cataclysm

### ISSUE THREAD

**Issue by Diabolicseiker** [Sonnenlicht-as/Trajectory-Estimation#8]
When eating, the game crashes. First time writing a report on a mod so thats as much as I can provide. 
[crash-2024-07-14_23.22.51-client.txt](https://github.com/user-attachments/files/16230671/crash-2024-07-14_23.22.51-client.txt)

**Comment by DuskCrow19** [comment]
I got the same error with the mod version 1.0.2 forge minecraft 1..20.1
