### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by YOUHAMO** [Sonnenlicht-as/Trajectory-Estimation#9]
when i put the mod in the mods folder and try to launch minecraft it doesnt launch

error code: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
Replace mod 'Fabric Loader' (fabricloader) 0.15.11 with version 0.16.3 or later.
More details:
<html>Mod 'Trajectory Estimation' (trajectory_estimation) 1.0.3 requires version 0.16.3 or later of mod 'Fabric Loader'<br>(fabricloader), but only the wrong version is present: 0.15.11!</html>
<html>Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14-<br>(inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.14' (viafabric-mc1144) 0.4.14+74-main requires version 1.14.4 of 'Minecraft' (minecraft), but only<br>the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.15' (viafabric-mc1152) 0.4.14+74-main requires version 1.15.2 of 'Minecraft' (minecraft), but only<br>the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.16' (viafabric-mc1165) 0.4.14+74-main requires version 1.16.5 of 'Minecraft' (minecraft), but only<br>the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.17' (viafabric-mc1171) 0.4.14+74-main requires version 1.17.1 of 'Minecraft' (minecraft), but only<br>the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.18' (viafabric-mc1182) 0.4.14+74-main requires version 1.18.2 of 'Minecraft' (minecraft), but only<br>the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.19' (viafabric-mc1194) 0.4.14+74-main requires version 1.19.4 of 'Minecraft' (minecraft), but only<br>the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.20.1' (viafabric-mc1201) 0.4.14+74-main requires version 1.20.1 of 'Minecraft' (minecraft), but<br>only the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.20.4' (viafabric-mc1204) 0.4.14+74-main requires version 1.20.3 or version 1.20.4 of 'Minecraft'<br>(minecraft), but only the wrong version is present: 1.21!</html>
<html>Mod 'ViaFabric for 1.20.5/6' (viafabric-mc1206) 0.4.14+74-main requires version 1.20.5 or version 1.20.6 of 'Minecraft'<br>(minecraft), but only the wrong version is present: 1.21!</html>

**Comment by MistyOrchid** [comment]
1.21 version？

**Comment by MistyOrchid** [comment]
Fixed in the new version 1.0.3.1
